<?php
if (!defined('ABSPATH')) exit;

class CPTT_Payment {
    private static $instance = null;
    const OPT = 'cptt_payment_settings';
    public static function instance(){ if(self::$instance===null) self::$instance=new self(); return self::$instance; }
    private function __construct(){
        add_action('admin_menu', [$this,'menu']);
        add_action('admin_post_cptt_pay_project', [$this,'render_pay_page']);
        add_action('admin_post_nopriv_cptt_pay_project', [$this,'render_pay_page']);
        add_action('admin_post_cptt_submit_card_receipt', [$this,'submit_card_receipt']);
        add_action('admin_post_nopriv_cptt_submit_card_receipt', [$this,'submit_card_receipt']);
        add_action('wp_ajax_cptt_approve_receipt', [$this,'ajax_approve_receipt']);
        add_action('wp_ajax_cptt_reject_receipt', [$this,'ajax_reject_receipt']);
    }
    public static function get_settings(){ return wp_parse_args(get_option(self::OPT,[]), ['active'=>'card','card_number'=>'','card_owner'=>'','zarinpal_merchant'=>'','zibal_merchant'=>'','idpay_api'=>'','nextpay_key'=>'','bank_gateway'=>'']); }
    public static function payment_url($project_id, $amount = 0){ return wp_nonce_url(admin_url('admin-post.php?action=cptt_pay_project&project_id='.(int)$project_id.'&amount='.(float)$amount), 'cptt_pay_project_'.(int)$project_id); }
    public function menu(){ add_submenu_page('edit.php?post_type=cptt_project','پرداخت‌ها','پرداخت‌ها','manage_options','cptt-payments',[$this,'page']); }
    public function page(){
        if(!current_user_can('manage_options')) return;
        if(!empty($_POST['cptt_payment_nonce']) && wp_verify_nonce($_POST['cptt_payment_nonce'],'cptt_payment_save')){
            update_option(self::OPT, [
                'active'=>sanitize_key($_POST['active']??'card'), 'card_number'=>sanitize_text_field($_POST['card_number']??''), 'card_owner'=>sanitize_text_field($_POST['card_owner']??''),
                'zarinpal_merchant'=>sanitize_text_field($_POST['zarinpal_merchant']??''), 'zibal_merchant'=>sanitize_text_field($_POST['zibal_merchant']??''), 'idpay_api'=>sanitize_text_field($_POST['idpay_api']??''), 'nextpay_key'=>sanitize_text_field($_POST['nextpay_key']??''), 'bank_gateway'=>sanitize_text_field($_POST['bank_gateway']??''),
            ], false); echo '<div class="notice notice-success"><p>تنظیمات ذخیره شد.</p></div>';
        }
        $s=self::get_settings();
        ?>
        <div class="wrap" dir="rtl"><h1>درگاه‌ها و پرداخت</h1><form method="post" style="max-width:760px;background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:18px;box-shadow:0 8px 24px rgba(15,23,42,.06)"><?php wp_nonce_field('cptt_payment_save','cptt_payment_nonce'); ?>
        <table class="form-table"><tr><th>روش فعال</th><td><select name="active"><option value="card" <?php selected($s['active'],'card'); ?>>کارت به کارت + رسید</option><option value="zarinpal" <?php selected($s['active'],'zarinpal'); ?>>زرین‌پال</option><option value="zibal" <?php selected($s['active'],'zibal'); ?>>زیبال</option><option value="idpay" <?php selected($s['active'],'idpay'); ?>>آیدی‌پی</option><option value="nextpay" <?php selected($s['active'],'nextpay'); ?>>نکست‌پی</option><option value="bank" <?php selected($s['active'],'bank'); ?>>درگاه اختصاصی بانکی</option><option value="bale" <?php selected($s['active'],'bale'); ?>>پرداخت داخلی بله</option></select><p class="description">درگاه‌های آنلاین به‌صورت زیرساخت آماده شده‌اند؛ کلیدهای هر درگاه را وارد کنید. کارت‌به‌کارت کامل فعال است.</p></td></tr>
        <tr><th>شماره کارت</th><td><input name="card_number" value="<?php echo esc_attr($s['card_number']); ?>" class="regular-text"></td></tr><tr><th>نام صاحب کارت</th><td><input name="card_owner" value="<?php echo esc_attr($s['card_owner']); ?>" class="regular-text"></td></tr>
        <tr><th>زرین‌پال Merchant</th><td><input name="zarinpal_merchant" value="<?php echo esc_attr($s['zarinpal_merchant']); ?>" class="regular-text"></td></tr><tr><th>زیبال Merchant</th><td><input name="zibal_merchant" value="<?php echo esc_attr($s['zibal_merchant']); ?>" class="regular-text"></td></tr><tr><th>IDPay API</th><td><input name="idpay_api" value="<?php echo esc_attr($s['idpay_api']); ?>" class="regular-text"></td></tr><tr><th>NextPay Key</th><td><input name="nextpay_key" value="<?php echo esc_attr($s['nextpay_key']); ?>" class="regular-text"></td></tr><tr><th>درگاه بانکی</th><td><input name="bank_gateway" value="<?php echo esc_attr($s['bank_gateway']); ?>" class="regular-text" placeholder="ملت / سامان / ملی ..."></td></tr>
        </table><p><button class="button button-primary">ذخیره</button></p></form><?php $this->receipts_table(); ?></div><?php
    }
    private function receipts_table(){
        $q=new WP_Query(['post_type'=>'cptt_payment_receipt','post_status'=>'any','posts_per_page'=>50]);
        echo '<h2>رسیدهای کارت به کارت</h2><table class="widefat striped"><thead><tr><th>پروژه</th><th>مشتری</th><th>مبلغ</th><th>رسید</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>';
        foreach($q->posts as $p){ $pid=(int)get_post_meta($p->ID,'project_id',true); $uid=(int)get_post_meta($p->ID,'user_id',true); $amount=(float)get_post_meta($p->ID,'amount',true); $att=(int)get_post_meta($p->ID,'attachment_id',true); $st=get_post_meta($p->ID,'status',true)?:'pending'; $u=$uid?get_user_by('id',$uid):null; echo '<tr><td>'.esc_html(get_the_title($pid)).'</td><td>'.esc_html($u?$u->display_name:'—').'</td><td>'.number_format($amount).'</td><td>'.($att?'<a href="'.esc_url(wp_get_attachment_url($att)).'" target="_blank">مشاهده</a>':'—').'</td><td>'.esc_html($st).'</td><td><button class="button cptt-approve-receipt" data-id="'.$p->ID.'">تایید</button> <button class="button cptt-reject-receipt" data-id="'.$p->ID.'">رد</button></td></tr>'; }
        echo '</tbody></table><script>jQuery(function($){$(document).on("click",".cptt-approve-receipt,.cptt-reject-receipt",function(){var b=$(this),fd=new FormData();fd.append("action",b.hasClass("cptt-approve-receipt")?"cptt_approve_receipt":"cptt_reject_receipt");fd.append("id",b.data("id"));fd.append("nonce","'.esc_js(wp_create_nonce('cptt_payment_nonce')).'");fetch(ajaxurl,{method:"POST",body:fd}).then(r=>r.json()).then(j=>{if(j.success)location.reload();else alert(j.data||"خطا")});});});</script>';
    }
    public function render_pay_page(){
        $pid=absint($_GET['project_id']??0); if(!$pid) wp_die('پروژه نامعتبر است.');
        $amount=(float)($_GET['amount']??0); if(!$amount && class_exists('CPTT_Expert')) { /* no-op */ }
        $steps=get_post_meta($pid,'_cptt_steps',true); if(!$amount && is_array($steps)){ foreach($steps as $st){ $amount+=(float)($st['cost']??0)-(float)($st['paid']??0); } }
        $s=self::get_settings(); header('Content-Type:text/html; charset=utf-8'); ?>
        <!doctype html><html dir="rtl" lang="fa"><head><meta charset="utf-8"><title>پرداخت پروژه</title><style>body{font-family:tahoma;background:#f8fafc;margin:0;padding:20px}.box{max-width:560px;margin:30px auto;background:#fff;border:1px solid #e5e7eb;border-radius:24px;padding:22px;box-shadow:0 20px 50px rgba(15,23,42,.1)}.amount{font-size:30px;font-weight:900;color:#4f46e5}.card{background:linear-gradient(135deg,#111827,#4f46e5);color:#fff;border-radius:18px;padding:18px;margin:16px 0}.btn{background:#16a34a;color:#fff;border:0;border-radius:12px;padding:12px 18px;font-weight:900;cursor:pointer}</style></head><body><div class="box"><h1>پرداخت بدهی پروژه</h1><p><?php echo esc_html(get_the_title($pid)); ?></p><div class="amount"><?php echo number_format(max(0,$amount)); ?> تومان</div><?php if($s['active']==='card' || true): ?><div class="card"><div>شماره کارت</div><h2><?php echo esc_html($s['card_number'] ?: 'تنظیم نشده'); ?></h2><div><?php echo esc_html($s['card_owner']); ?></div></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" enctype="multipart/form-data"><input type="hidden" name="action" value="cptt_submit_card_receipt"><input type="hidden" name="project_id" value="<?php echo esc_attr($pid); ?>"><input type="hidden" name="amount" value="<?php echo esc_attr(max(0,$amount)); ?>"><?php wp_nonce_field('cptt_submit_card_receipt_'.$pid,'nonce'); ?><p><label>آپلود رسید پرداخت<br><input type="file" name="receipt" required></label></p><button class="btn">ثبت رسید برای تایید مدیر</button></form><?php endif; ?></div></body></html><?php exit;
    }
    public function submit_card_receipt(){ $pid=absint($_POST['project_id']??0); check_admin_referer('cptt_submit_card_receipt_'.$pid,'nonce'); $amount=(float)($_POST['amount']??0); require_once ABSPATH.'wp-admin/includes/file.php'; require_once ABSPATH.'wp-admin/includes/media.php'; require_once ABSPATH.'wp-admin/includes/image.php'; $att=0; if(!empty($_FILES['receipt']['name'])) $att=media_handle_upload('receipt',0); $rid=wp_insert_post(['post_type'=>'cptt_payment_receipt','post_status'=>'publish','post_title'=>'رسید پرداخت پروژه #'.$pid]); update_post_meta($rid,'project_id',$pid); update_post_meta($rid,'user_id',get_current_user_id()); update_post_meta($rid,'amount',$amount); update_post_meta($rid,'attachment_id',is_wp_error($att)?0:(int)$att); update_post_meta($rid,'status','pending'); if(class_exists('CPTT_Core')) CPTT_Core::activity_log('payment_receipt',$rid,'receipt_submitted','ثبت رسید پرداخت پروژه #'.$pid); wp_die('رسید شما ثبت شد و پس از تایید مدیر در حساب پروژه اعمال می‌شود.'); }
    public function ajax_approve_receipt(){ check_ajax_referer('cptt_payment_nonce','nonce'); if(!current_user_can('manage_options')) wp_send_json_error('no_access'); $id=absint($_POST['id']??0); $pid=(int)get_post_meta($id,'project_id',true); $amount=(float)get_post_meta($id,'amount',true); update_post_meta($id,'status','approved'); if(class_exists('CPTT_Core')){ CPTT_Core::ledger_add(['project_id'=>$pid,'type'=>'customer_card_payment','amount'=>$amount,'note'=>'تایید رسید کارت به کارت']); CPTT_Core::activity_log('payment_receipt',$id,'receipt_approved','تایید رسید و ثبت پرداخت پروژه #'.$pid); } $this->apply_payment_to_project($pid,$amount); wp_send_json_success(); }
    public function ajax_reject_receipt(){ check_ajax_referer('cptt_payment_nonce','nonce'); if(!current_user_can('manage_options')) wp_send_json_error('no_access'); update_post_meta(absint($_POST['id']??0),'status','rejected'); wp_send_json_success(); }
    private function apply_payment_to_project($pid,$amount){ $steps=get_post_meta($pid,'_cptt_steps',true); if(!is_array($steps)) return; $left=$amount; foreach($steps as &$st){ $remain=max(0,(float)($st['cost']??0)-(float)($st['paid']??0)); if($remain<=0) continue; $pay=min($left,$remain); $st['paid']=(float)($st['paid']??0)+$pay; $left-=$pay; if($left<=0) break; } unset($st); update_post_meta($pid,'_cptt_steps',$steps); }
}
